test: add binlog replication tests for log file based positioning

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -54,8 +54,14 @@ jobs:
         cat query.log | grep -e "^--- " | sed 's/--- //g' | awk 'BEGIN {count=1} {printf "%d. %s\n", count++, $0}'
         cat query.log | grep -q "FAIL" && exit 1 || exit 0
 
-    - name: Test Binlog Replication
+    - name: Test Binlog Replication With GTID Enabled
       run: |
-        go test -v -p 1 --timeout 600s ./binlogreplication | tee replication.log
+        GTID_ENABLED=true go test -v -p 1 --timeout 600s ./binlogreplication | tee replication.log
+        cat replication.log | grep -e "^--- " | sed 's/--- //g' | awk 'BEGIN {count=1} {printf "%d. %s\n", count++, $0}'
+        cat replication.log | grep -q "FAIL" && exit 1 || exit 0
+
+    - name: Test Binlog Replication With GTID Disabled
+      run: |
+        GTID_ENABLED=false go test -v -p 1 --timeout 600s ./binlogreplication | tee replication.log
         cat replication.log | grep -e "^--- " | sed 's/--- //g' | awk 'BEGIN {count=1} {printf "%d. %s\n", count++, $0}'
         cat replication.log | grep -q "FAIL" && exit 1 || exit 0
